version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "multi-region-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xh5xqmwzijb8"
s3_prefix = "multi-region-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
