version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-multiregions"
s3_prefix = "hello-world-multiregions"
region = "eu-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENVTYPE=\"dev\""
